# Generated by Django 2.2 on 2022-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['company', 'position', 'explanation', 'category']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'email', 'phone_number', 'department', 'date_of_birth', 'cv']},
        ),
        migrations.AddField(
            model_name='advert',
            name='users',
            field=models.ManyToManyField(to='mysite.User'),
        ),
    ]
