# Generated by Django 2.2 on 2022-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20220701_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
