# Generated by Django 2.2 on 2022-07-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20220701_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Advert')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User')),
            ],
        ),
    ]
