# Generated by Django 2.2 on 2022-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20220707_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'email', 'phone_number', 'department', 'date_of_birth']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
